import time

print("\nInitializing system......")
time.sleep(2)
print("\nWaiting for user to get connect ")
time.sleep(3)
print("\nStarting Brute Force Attack ")
time.sleep(1)
print("\nTrying to gaining root access")
time.sleep(4)
print("\nFinished ")
time.sleep(1)
print("\nUsername:'Dell-1'")
time.sleep(1)
print("\nPassword: may21@1996")
time.sleep(1)
print("\nEncrypting user's system")
time.sleep(5)
print("\nGenerating decryption key")
time.sleep(3)
print("\nDone")
print("\nDecryption key for 'Dell-1' is 'fx56bnh$#kkbha#4yukm&$$$kbsxx' ")
time.sleep(1)
print("\nAttack Successful \n")
